Remove debug cncf/cnf-testsuite#1064

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -240,7 +240,7 @@ jobs:
     - name: Maximize build space
       uses: easimon/maximize-build-space@master
       with:
-        root-reserve-mb: 20000
+        root-reserve-mb: 35000
         swap-size-mb: 100
         remove-dotnet: 'true'
         remove-android: 'true'
@@ -286,23 +286,21 @@ jobs:
         shards install
         crystal src/cnf-testsuite.cr setup 
         helm repo add stable https://cncf.gitlab.io/stable
-        # if ! [ -f "/tmp/airgapped.tar.gz" ]; then 
-        #       echo "Cached airgapped.tar.gz not found, re-creating airgapped.tar.gz"
-        #       LOG_LEVEL=info crystal src/cnf-testsuite.cr airgapped output-file=/tmp/airgapped.tar.gz
-        #       LOG_LEVEL=info crystal src/cnf-testsuite.cr cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz
-        # else
-        #       echo "Cached airgapped.tar.gz file found, using cache for JOB_ID: $GITHUB_JOB"
-        # fi
-        # echo "Checking for CoreDNS"
-        # tar -C /tmp/ -xvf /tmp/airgapped.tar.gz
-        # if [ -f "/tmp/images/coredns_1.6.7.tar" ]; then
-        #    echo "CoreDNS found, CNF Setup Ran."
-        # else
-        #    echo "CoreDNS not found, Re-Running CNF Setup."
-        #    LOG_LEVEL=debug crystal src/cnf-testsuite.cr cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz
-        # fi
-    - name: Setup tmate session
-      uses: mxschmitt/action-tmate@v3
+        if ! [ -f "/tmp/airgapped.tar.gz" ]; then 
+              echo "Cached airgapped.tar.gz not found, re-creating airgapped.tar.gz"
+              LOG_LEVEL=info crystal src/cnf-testsuite.cr airgapped output-file=/tmp/airgapped.tar.gz
+              LOG_LEVEL=info crystal src/cnf-testsuite.cr cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz
+        else
+              echo "Cached airgapped.tar.gz file found, using cache for JOB_ID: $GITHUB_JOB"
+        fi
+        echo "Checking for CoreDNS"
+        tar -C /tmp/ -xvf /tmp/airgapped.tar.gz
+        if [ -f "/tmp/images/coredns_1.6.7.tar" ]; then
+           echo "CoreDNS found, CNF Setup Ran."
+        else
+           echo "CoreDNS not found, Re-Running CNF Setup."
+           LOG_LEVEL=debug crystal src/cnf-testsuite.cr cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz
+        fi
     - name: Create Cluster & Run Tests.
       run: |
         sed -i "/${{ matrix.test }}/a \ \ required: true" $(pwd)/embedded_files/points.yml
