Add tests for chaos test running in airgapped mode cncf/cnf-testsuite#962

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -235,6 +235,82 @@ jobs:
         docker volume prune -f || true
         docker network prune -f || true
         
+  chaos-airgapped:
+    name: Chaos Tests
+    needs: [tests]
+    runs-on: [ubuntu-latest]
+    strategy:
+      fail-fast: false
+      matrix:
+        tag: ["chaos_container_kill", "chaos_cpu_hog", "pod_delete", "pod_io_stress", "pod_memory_hog", "pod_network_latency", "disk_fill"]
+    env:
+      OFFLINE_IMAGE: "conformance/offline:crystal-1.0.0-r1"
+    steps: 
+    - name: Checkout code
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+    - name: Cleanup Tmp DIR
+      run: |
+        sudo rm -rf /tmp/*
+    - name: Cache crystal shards
+      uses: actions/cache@v2
+      env:
+        cache-name: cache-crystal-shards
+      with:
+        path: ./lib
+        key: lib-${{ hashFiles('**/shard.lock') }}
+        restore-keys: |
+          lib-
+    - name: Cache airgapped.tar.gz
+      uses: actions/cache@v2
+      env:
+        cache-name: cache-airgapped-tar
+      with:
+        path: /tmp/airgapped.tar.gz
+        key: airgapped-$GITHUB_JOB-${{ hashFiles('**/src/tasks/airgap.cr', '**/src/tasks/utils/airgap.cr', '**/src/tasks/utils/airgap_utils.cr', '**/src/tasks/utils/tar.cr') }}
+    - name: Create airgapped.tar.gz if one is not found in cache
+      run: |
+        shards install
+        crystal src/cnf-testsuite.cr setup 
+        helm repo add stable https://cncf.gitlab.io/stable
+        if ! [ -f "/tmp/airgapped.tar.gz" ]; then 
+              crystal src/cnf-testsuite.cr airgapped output-file=/tmp/airgapped.tar.gz
+              LOG_LEVEL=debug crystal src/cnf-testsuite.cr cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz
+        else
+              echo "Cached airgapped.tar.gz file found, using cache for JOB_ID: $GITHUB_JOB"
+        fi
+        echo "Checking for CoreDNS"
+        tar -C /tmp/ -xvf /tmp/airgapped.tar.gz
+        if [ -f "/tmp/images/coredns_1.6.7.tar" ]; then
+           echo "CoreDNS found, CNF Setup Ran."
+        else
+           echo "CoreDNS not found, Re-Running CNF Setup."
+           LOG_LEVEL=debug crystal src/cnf-testsuite.cr cnf_setup cnf-config=sample-cnfs/sample_coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz
+        fi
+    - name: Create Cluster & Run Tests.
+      env:
+        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+      run: |
+        export DIR=$(uuidgen)
+        echo "export DIR=$DIR" > dir.env
+        mkdir /shared/$DIR
+        cp -a $(pwd) /shared/$DIR/cnf-testsuite
+        cp /tmp/airgapped.tar.gz /shared/$DIR/
+        docker run --entrypoint=/bin/bash --name $DIR-shards -v /shared/$DIR/cnf-testsuite:/cnf-testsuite -t $OFFLINE_IMAGE -c "shards install"
+        docker run --name $DIR --network none --privileged -v /shared/$DIR/cnf-testsuite:/cnf-testsuite -v /shared/$DIR/airgapped.tar.gz:/airgapped/airgapped.tar.gz -v /shared/$DIR/tmpdata:/tmp -t $OFFLINE_IMAGE /bin/bash -c "LOG_LEVEL=info crystal src/cnf-testsuite.cr setup offline=/airgapped/airgapped.tar.gz && LOG_LEVEL=info crystal src/cnf-testsuite.cr install_litmus offline=true && ./.github/workflows/check_litmus.sh && LOG_LEVEL=info crystal src/cnf-testsuite.cr cnf_setup cnf-config=./example-cnfs/coredns/cnf-testsuite.yml input-file=/airgapped/airgapped.tar.gz && LOG_LEVEL=info crystal src/cnf-testsuite.cr ${{ matrix.tag }} offline=true verbose"
+    - name: Delete Cluster
+      if: ${{ always() }}
+      run: |
+        source dir.env
+        docker rm -f $DIR
+        docker rm -f $DIR-shards
+        sudo rm -rf /shared/$DIR
+        sudo rm -rf /tmp/*
+        docker container prune -f || true
+        docker volume prune -f || true
+        docker network prune -f || true
+
   build:
     name: Build Release
     runs-on: ubuntu-latest
