Move debug cncf/cnf-testsuite#1064

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -280,29 +280,29 @@ jobs:
       with:
         path: /tmp/airgapped.tar.gz
         key: airgapped-$GITHUB_JOB-${{ hashFiles('**/utils/airgap/airgap.cr', '**/src/tasks/utils/cnf_manager.cr') }}
-    - name: Setup tmate session
-      uses: mxschmitt/action-tmate@v3
     - name: Create airgapped.tar.gz if one is not found in cache
       run: |
         shards install
         crystal src/cnf-testsuite.cr setup 
         sudo rm -rf /tmp/ ; sudo mkdir /tmp ; sudo mount /dev/buildvg/buildlv /tmp
-        helm repo add stable https://cncf.gitlab.io/stable
-        if ! [ -f "/tmp/airgapped.tar.gz" ]; then 
-              echo "Cached airgapped.tar.gz not found, re-creating airgapped.tar.gz"
-              crystal src/cnf-testsuite.cr airgapped output-file=/tmp/airgapped.tar.gz
-              LOG_LEVEL=debug crystal src/cnf-testsuite.cr cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz
-        else
-              echo "Cached airgapped.tar.gz file found, using cache for JOB_ID: $GITHUB_JOB"
-        fi
-        echo "Checking for CoreDNS"
-        tar -C /tmp/ -xvf /tmp/airgapped.tar.gz
-        if [ -f "/tmp/images/coredns_1.6.7.tar" ]; then
-           echo "CoreDNS found, CNF Setup Ran."
-        else
-           echo "CoreDNS not found, Re-Running CNF Setup."
-           LOG_LEVEL=debug crystal src/cnf-testsuite.cr cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz
-        fi
+        # helm repo add stable https://cncf.gitlab.io/stable
+        # if ! [ -f "/tmp/airgapped.tar.gz" ]; then 
+        #       echo "Cached airgapped.tar.gz not found, re-creating airgapped.tar.gz"
+        #       crystal src/cnf-testsuite.cr airgapped output-file=/tmp/airgapped.tar.gz
+        #       LOG_LEVEL=debug crystal src/cnf-testsuite.cr cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz
+        # else
+        #       echo "Cached airgapped.tar.gz file found, using cache for JOB_ID: $GITHUB_JOB"
+        # fi
+        # echo "Checking for CoreDNS"
+        # tar -C /tmp/ -xvf /tmp/airgapped.tar.gz
+        # if [ -f "/tmp/images/coredns_1.6.7.tar" ]; then
+        #    echo "CoreDNS found, CNF Setup Ran."
+        # else
+        #    echo "CoreDNS not found, Re-Running CNF Setup."
+        #    LOG_LEVEL=debug crystal src/cnf-testsuite.cr cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz
+        # fi
+    - name: Setup tmate session
+      uses: mxschmitt/action-tmate@v3
     - name: Create Cluster & Run Tests.
       run: |
         sed -i "/${{ matrix.test }}/a \ \ required: true" $(pwd)/embedded_files/points.yml
